Merge branch
Pulatov-iOS/TBank_Swift-CodeUI-SwiftUI pull request #3
Opened 2024-03-21 21:02 UTC by MyDanchik

add select button and action sheet

2024-03-21 21:08 UTC, MyDanchik commented
![Simulator Screenshot - iPhone 15 Pro - 2024-03-22 at 00 08 35](https://github.com/Pulatov-iOS/TBank_Swift-CodeUI-SwiftUI/assets/99731538/728713fb-d111-4df9-b5e2-2a30822e0d01)
![Simulator Screenshot - iPhone 15 Pro - 2024-03-22 at 00 08 42](https://github.com/Pulatov-iOS/TBank_Swift-CodeUI-SwiftUI/assets/99731538/d5643275-460d-4926-a6bb-341a055505c7)

2024-03-22 07:38 UTC, Pulatov-iOS requested changes
Исправить ннедочеты

2024-03-22 07:38 UTC, Pulatov-iOS commented on TBank/Application/Modules/LocalizedCurrencyRates/LocalizedCurrencyRatesViewController.swift
> +    private var currencyRates: [CurrencyRate] = []
В контроллере не должны быть проперти с данными

2024-03-22 07:38 UTC, Pulatov-iOS commented on TBank/Application/Modules/LocalizedCurrencyRates/LocalizedCurrencyRatesViewController.swift
>      private func bindings() {
Удалить

2024-03-22 07:38 UTC, Pulatov-iOS commented on TBank/Application/Modules/LocalizedCurrencyRates/LocalizedCurrencyRatesViewController.swift
> +        NetworkManagerCurrency.shared.fetchExchangeRates { [weak self] rates in
Запрос должен быть в модели

2024-03-22 07:58 UTC, Pulatov-iOS approved these changes
Good

2024-03-22 07:59 UTC, merged